In [1]:
import io
import numpy as np
import time, os, sys
from urllib.parse import urlparse
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline
mpl.rcParams['figure.dpi'] = 300
from cellpose import utils, io, models
from cellpose import plot

In [2]:
model = models.Cellpose(gpu=True, model_type='cyto')

In [3]:
files = os.listdir("dataset/images_sophie")
imgs = [io.imread(f"dataset/images_sophie/{file}") for file in files]
masks, flows, styles, diams = model.eval(imgs, diameter=None, channels=[0,0])
io.masks_flows_to_seg(imgs, masks, flows, diams, files, [0,0])

100%|██████████| 37/37 [00:00<00:00, 6509.89it/s]
/home/nanaa/.conda/envs/cellpose/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/nanaa/.conda/envs/cellpose/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [7]:
import napari
print(masks[0])
viewer = napari.view_labels(masks[0], name='image')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
